# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a17553d9bd12dd2a97c19b574c377974b41178bf02aaa03991e70e6cd3d156d1cb62d15c01c084f45e135590bb64d8cdab71d6b4774ea7bd95eab345ff99b0b

test:
  secret_key_base: a2b71b0903edd0d2413bfed054c6cb3689eeeb484b159a9ed7257baa047cb9c4ecec588c31e00df713a7b6d8e0794eea75a22f67cb87e1fb03e564c8bdc8a0d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
